
export enum ApiNotificationTypes {
    REFRESH_NOTIFICATION = "REFRESH_NOTIFICATION",
    ADD_NEW_NOTIFICATION = "ADD_NEW_NOTIFICATION",
    SLOT_BOOKED_NOTIFICATION = "SLOT_BOOKED_NOTIFICATION",
    SLOT_DELETE_NOTIFICATION = "SLOT_DELETE_NOTIFICATION"
}

export enum SocketTriggerTypes {
    REGISTER_USER = "REGISTER_USER",
    RECEIVED_NOTIFICATION = "RECEIVED_NOTIFICATION",
    USER_SLOT_BOOKED = "USER_SLOT_BOOKED",
    USER_SLOT_UNBOOKED = "USER_SLOT_UNBOOKED",
}

// ? notification type
export enum NotificationType {
    FOLLOW = "FOLLOW",
    SLOT_CREATED = "SLOT_CREATED",
    SLOT_BOOKED = "SLOT_BOOKED",
    SLOT_UNBOOKED = "SLOT_UNBOOKED",
    SLOT_UPDATED = "SLOT_UPDATED",
    SLOT_DELETED = "SLOT_DELETED"
}